### ISSUE TITLE
Bug: no output from plotter when querying plotter help file

### ISSUE THREAD

**Issue by sensorium** [flucoma/flucoma-pd#100]
### Please tell us what you were doing! You can include code and files by drag and dropping them into the text area.

When mousing (and clicking/dragging) over the plotter in the plotter help file, no coordinates are output.  This is using the most recent release, I haven't tried compiling the current source.

### What was the expected result?

I expected the coordinates to show up in the list box at step (3).

### What was the actual result?

Nothing appeared in the list box connected to the plotter.

### What operating system were you using?

Mac

### Operating system version

MacOS 12.7.3

### FluCoMa Version

1.0.6

**Comment by tremblap** [comment]
Hello!

have you tried the nightly builds? it is corrected now but please confirm:
https://github.com/flucoma/flucoma-pd/releases

**Comment by sensorium** [comment]
Thanks, I tried the nightly build and it's the same - the "modified date" on everything in the help folder is still 29 March 2023.  I've tried the xy.pd file used in the plotter query help patch and I can't get coordinates out of it.

**Comment by sensorium** [comment]
Ooops, hold on!  I'm downloading again and this time it really looks like the nightly build.  Not sure what happened last time.  Apologies!

**Comment by sensorium** [comment]
The nightly build works!  Thanks so much.

**Comment by tremblap** [comment]
it was a bug introduced by Pd update. I'm about to do the official merge for a release but the nightlies are a good up to date contender.
