### ISSUE TITLE
fluid.bufnmf blocks bang till it finishes processing

### ISSUE THREAD

**Issue by muziker** [flucoma/flucoma-pd#16]
In fluid.bufnmf-help.pd, when i click on the bang to start [fluid.bufnmf], the bang doesn't highlight until fluid.bufnmf finishes processing. I'm not sure how the other pd objects do it, but usually the bang highlights and the object carries on processing.

**Comment by tremblap** [comment]
Hello! It is not an issue per se - all Pd object are on a single thread and the default threading is to stay in that thread... nmf is a huge process so it stalls the rest. But don't despair, check the top right of the help file, in [note_on_multithreading] and enjoy the blocking mode 0!
