### ISSUE TITLE
mishandling of downward count of numchannels in arrays

### ISSUE THREAD

**Issue by tremblap** [flucoma/flucoma-pd#17]
When one runs a process and decides to only take one channel of output, it seems that the (simulated) multichannel array check is not considering the destination channel count to allow a single array to be given as a destination.

In the attached example, which needs the fluid.bufpitch help patch to run, the stats are run only on the first channel of the bufpitch-feats multiarray by specifying -numchannels 1 - yet we get an error that is slightly comical:

> Not enough arrays to operate on pitchstats. Found 2 array(s) but need 1.

[bug.pd.zip](https://github.com/flucoma/flucoma-pd/files/7883231/bug.pd.zip)

**Comment by weefuzzy** [comment]
The attribute is `-numchans` not `-numchannels`

**Comment by weefuzzy** [comment]
Although it would be good if the error message made sense

**Comment by tremblap** [comment]
oops. sorry for the wrong bug report
