### ISSUE TITLE
instant crash with bufmfcc help in beta5

### ISSUE THREAD

**Issue by tremblap** [flucoma/flucoma-pd#32]
I reverted to beta4, but to reproduce, launch the helpfile of bufmfcc. I cannot compile in Test mode on my temp machine. @tedmoore in the manual UT was it on the list, and if so, did it work for you?

I'm downloading the nightly and the beta4 to see if it automagically disappeared.

**Comment by weefuzzy** [comment]
if it only happens in Test builds then its probably an assertion being thrown – is there a crash report in your console.app?

**Comment by weefuzzy** [comment]
```
Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   pd                            	0x0000000100021589 canvas_getargs + 89
```

🤷 none the wiser

**Comment by weefuzzy** [comment]
More stack trace from lldb: 
```
Thread 1 Queue : com.apple.main-thread (serial)
#0	0x0000000100021589 in canvas_getargs ()
#1	0x000000010004f928 in canvas_objtext ()
#2	0x0000000100051bac in canvas_obj ()
#3	0x0000000100063965 in pd_typedmess ()
#4	0x000000010005e77d in binbuf_eval ()
#5	0x0000000100062f6f in binbuf_evalfile ()
#6	0x0000000100020a82 in glob_evalfile ()
#7	0x00000001000750da in open_via_helppath ()
#8	0x000000010002876a in canvas_done_popup ()
#9	0x0000000100063b15 in pd_typedmess ()
#10	0x0000000100063cb3 in pd_typedmess ()
#11	0x000000010005e77d in binbuf_eval ()
#12	0x000000010006deb4 in socketreceiver_read ()
#13	0x000000010006d17c in sys_domicrosleep ()
#14	0x000000010006ead2 in sys_pollgui ()
#15	0x000000010006860f in m_mainloop ()
#16	0x0000000100071b81 in sys_main ()
#17	0x0000000100000d34 in start ()
```

Don't see anything of ours in there, unless we're overrunning and corrupting something. Has this help file changed recently?

**Comment by tremblap** [comment]
oh I might have corrupted the file when I changed it with grep. I'll revert the 4 files to pre-beta5 and correctly correct them - more soon.

**Comment by tremblap** [comment]
ok my bad - and I don't know why it worked before I did the PR that corrupted it. Sorry for the noise. I don't know how we can warn the Pd community that 4 helpfiles will crash Pd on Mac though, I'll certainly push right to dev

**Comment by tremblap** [comment]
fixed in dev
