### ISSUE TITLE
`fluid.bufflatten` stalls after first call in release builds

### ISSUE THREAD

**Issue by tremblap** [flucoma/flucoma-pd#33]
the same code in Max and SC is attached, to show the expected behaviour. this sounds like an hilarious wrapper-api problem @weefuzzy I am sorry.

When running this code, which is 3 consecutive frames of 13 channels, into bufstats, it corrupts the object, to the point that only a restart of Pd solves it - even reinstantiating the object doesn't.

attached code to reproduce in Pd and reassure in Max and SC
[Archive.zip](https://github.com/flucoma/flucoma-pd/files/8192375/Archive.zip)
.

**Comment by tremblap** [comment]
How to reproduce:
1. fill a buffer with 3 consecutive identical frames - click on the right message [13]
2. run the stats (left button)
3. check the values
4. make another source buffer (13 again) randomly
5. run the stats
6. the values are the same - this is why I call it corrupting the object - instead of being the new stats.

**Comment by tremblap** [comment]
not in this patch but i should add a check - in the other patch I was
checking at  every point and I am 95% certain that was where it stalles

**Comment by tremblap** [comment]
ok I got it to stall in the other patch (first time) - maybe as it is more complex it helps - I'll send it to you. I'll try to run it with TEST. The good news is that I was right - the input to stats changes, but not its output.

**Comment by tremblap** [comment]
and I got it to stall in Test (including non-optimised-code-bonus-crackle) without crashing. Just a few restarts of the patch got it in the place of stalling. happy to walk through the patch if that helps
[mlp-class2tech.pd.zip](https://github.com/flucoma/flucoma-pd/files/8199956/mlp-class2tech.pd.zip)
.

**Comment by weefuzzy** [comment]
So the issue turns out to be in `bufflatten` and with release builds. Temporary views of buffer adaptors in chained function calls are getting important things optimised out, and this is partly a consequence of the hacky way we pretend there are multichannel buffers in PD.

**Comment by weefuzzy** [comment]
Workaround is to make local variables for these temporaries, and then all is fine. Better would be to be able to solve this in the PD wrapper, but that eludes me at the moment.

**Comment by tremblap** [comment]
fixed thanks
