### ISSUE TITLE
mlpregressor.pd?

### ISSUE THREAD

**Issue by ormf** [flucoma/flucoma-pd#40]
Hi,

 I'm trying to do mlpregression in pure data but can't find the respective objects, even after compiling from source. Aren't they included in the distribution? Is this documented somewhere?

--
Orm

**Comment by ormf** [comment]
Hi James, thanks a lot, that works! If it isn't mentioned anywhere in the docs maybe it'd be good to do so. 
BTW (in case you don't know it): You don't necessarily have to load the lib on startup but could also load the lib using the "declare" object like this:
![mlpregerssor](https://user-images.githubusercontent.com/11195558/164403346-113ec18c-dfbb-4206-a299-2249dc539c69.png)



I'll work through the Max/MSP example and will port it to pd for reference. Would anyone be interested to include it in the repository?

**Comment by jamesb93** [comment]
It may not be obviated enough by the docs but the "QuickStart.md" file describes these things:

https://github.com/flucoma/flucoma-pd/blob/main/QuickStart.md

Where might you expect to read it so we can make it more immediate. I realise GitHub gives you instructions on compiling rather than on installing so maybe that's the place?

Another question is, how idiomatic is it to use `declare` over setting up your libs via the preferences?



> I'll work through the Max/MSP example and will port it to pd for reference. Would anyone be interested to include it in the repository?

It depends on where @tremblap is at, but I definitely think he (as the main `pd` maintainer) would appreciate community contributions especially from what I sense to be a seasoned user ;)

**Comment by tremblap** [comment]
Hello!

Indeed we should mention it in the doc. I wonder if we should do belt and braces and include a declare -lib as well as instructions for proper installation...

as for translating, i can send you the 6 from the Max youtube tutorials (mlpregressor mlpclassifier and the 4 2d navigation) - the example folder of the max package is in mutation at the moment, and some of it is translated already, and the helpfiles are being translated so at the moment pd has 3 versions cohabitating:
- the new blue-header format (translated)
- the old grey format (old max translated)
- the instantiation test ones (embarrassingly not good)

with a few exception (a few blue and a few grey unfinished / in progress)

but the good news is that we have someone working with me to translate at least all the helpfiles in the next few months. If you want to join, I can let you know what we haven't got on our radar and any help is definitely welcome!

**Comment by tremblap** [comment]
> I looked for a replacement doing it all within pd and found flucoma. 

ok I've attached the example that is doing a regressor - the same as this video in Max: https://www.youtube.com/watch?v=3XSy297v9vk

> In example patches I would definitely recommend declare statements as they take care of loading libraries without having to set it up in the preferences.

ok I'll keep that in mind for my translation.

thanks for the offer to help, and feel free to send comments/offer/code along.
[Archive.zip](https://github.com/flucoma/flucoma-pd/files/8532778/Archive.zip)

**Comment by ormf** [comment]
What I forgot: It is common practise to put a version statement into the setup routine in a pd lib. That way you see when and whether pd loads a library and which version gets loaded.

So the last line in the definition of fluid_libmanipulation_setup in fluid_libmanipulation.cpp should contain something like

`post("fluid_libmanipulation: 1.0.0-TB2.beta6");`

Not sure where this has to be put for cmake to generate libmanipulation.cpp accordingly, so I couldn't issue a pull request, but maybe you want to add this.

**Comment by tremblap** [comment]
@weefuzzy and I tried to not pollute the post window... hence the optional version message. We'll consider. I also thought of adding it to the (updated) overview (attached here
[FluidCorpusManipulationOverview.pd.zip](https://github.com/flucoma/flucoma-pd/files/8532858/FluidCorpusManipulationOverview.pd.zip)
)

**Comment by ormf** [comment]
I see your point and definitely agree about post window pollution, but one line should be ok, especially since I don't know of any pd lib which doesn't do this as there is no way to tell, whether a lib has been loaded, because pd unfortunately doesn't issue an error message if it can't find a library to load (in contrast to an external).

**Comment by ormf** [comment]
I made a small fix in the mlpregression example (taking care the xy-plot doesn't draw out of bounds and fixing the coordinate range). How can I submit?

**Comment by jamesb93** [comment]
If you're comfortable with GitHub you can make a pull request. Otherwise linking the patch inline here is already helpful!

**Comment by tremblap** [comment]
Submitting here, or even better on the discourse since these are not included in the package (yet)

**Comment by ormf** [comment]
I'll attach here. I'd be grateful to get pointers how to enter discourse as I guess this is getting too much off-topic for a closed issue ;-)

[mlp-example.zip](https://github.com/flucoma/flucoma-pd/files/8539598/mlp-example.zip)

**Comment by tremblap** [comment]
https://discourse.flucoma.org/

top right: sign up button

I'll take your example and update mine, then push it when I updated with the new interface on the example folder I think. @jamesb93 and @tedmoore and I are meeting on monday to talk about their future across CCEs (Max Pd and SC)

**Comment by ormf** [comment]
I did that 6 days ago and after signing up got notified that it needs approval. I didn't hear back yet and now my name is taken ;-) Icould repeat with a different but would prefer using "orm"...

**Comment by weefuzzy** [comment]
If your name is taken then you probably did get approved but the notification either didn't happen or went into your junk. I'm beginning to suspect this might be happening a lot because I keep approving users who then don't post anything!

**Comment by tremblap** [comment]
maybe we should put a note on discourse for people to check their junk mail - the approval is usually within one working day, I log every day for sure and approve right away (we administrators get a red dot, almost impossible to miss!)

**Comment by ormf** [comment]
I just reset my password and it worked, thanks for the input! Is there a place/topic/forum dedicated to pd? 

I'm on linux and can volunteer to check out things related to it (it seems most people here are on OSX). BTW: the ending ".pd_linux" for abstractions is ok, but I suggest to specify the processor architecture (".l_ia64" for 64-bit and ".l_i386" for 32-bit) for disambiguation (and maybe even provide 32-bit binaries). pd will first search for the architecture-specific binaries before resorting to .pd_linux.

**Comment by weefuzzy** [comment]
> BTW: the ending ".pd_linux" for abstractions is ok, but I suggest to specify the processor architecture (".l_ia64" for 64-bit and ".l_i386" for 32-bit) for disambiguation (and maybe even provide 32-bit binaries). pd will first search for the architecture-specific binaries before resorting to .pd_linux.

I'll make a new issue to review this in the CMake. Is there a good place to find the best things to do for arm64, and for other OSes (e.g. does this apply to `pd_darwin` on macOS too? What about Windows?). 

We dropped 32-bit packages a while ago, primarily because the Apple tooling has stopped supporting it. Is there still widespread demand for 32-bit stuff?

**Comment by ormf** [comment]
@weefuzzy  

> (e.g. does this apply to pd_darwin on macOS too? What about Windows?) 

I don't know (asked about in on pd's ML sometime ago but never got a response).

> Is there still widespread demand for 32-bit stuff?

As pd runs on about any hardware on embedded Linux I could imagine there's use for it. I still do have some old laptops lying around with 32bit architecture, but I wouldn't give it too much thought. OTOH as it's just a compile flag it's not difficult to support it.
