### ISSUE TITLE
fluid.dataset objects missing

### ISSUE THREAD

**Issue by JRSV** [flucoma/flucoma-pd#6]
Hello,

I have compilled from source and downloaded the package, in neither I can find the fluid.dataset objects.

**Comment by weefuzzy** [comment]
Hey Raf, 

Good to hear from you. All the `fluid.dataset~` and objects that consume or operate on them live together in `fluid.libmanipulation.mxo`, because this is the simplest way to enable them to communicate with each other.

**Comment by weefuzzy** [comment]
Can Max instantiate `[fluid.dataset~]` ok?

**Comment by weefuzzy** [comment]
Sorry, thought this was max at first. 

In PD, you need to add `fluid_libmanipulation` as a library in your startup preferences, so that the bundle gets loaded

**Comment by weefuzzy** [comment]
This is all brand new for PD, so docs are lagging slightly, sorry about that. We'll update the README asap, as that's pretty important 😬

**Comment by JRSV** [comment]
Hi Owen!! yes... don't forget I am linux/pd guy haha
ok, a `declare -lib fluid_libmanipulation` object in the help file is enough for now.
thanks Owen!!
