### ISSUE TITLE
fluid.dataset and fluid.datasetquery objects missing

### ISSUE THREAD

**Issue by grrrr** [flucoma/flucoma-pd#70]
Hi, with download version 1.0.2 of [FluCoMa-PD-Mac.dmg](https://github.com/flucoma/flucoma-pd/releases/download/1.0.2/FluCoMa-PD-Mac.dmg) the `fluid.dataset` and `fluid.datasetquery` objects are missing. The respective helpfiles are there.

**Comment by tremblap** [comment]
it is a library, they are all included in fluid_libmanipulation - see learn.flucoma.org/installation for a painless install.

**Comment by jarmitage** [comment]
Suggestion: link to learn.flucoma.org/installation in this readme
