### ISSUE TITLE
fluid.wavefrom error

### ISSUE THREAD

**Issue by delmenhorst** [flucoma/flucoma-pd#74]
Hi,

fluid.waveform produces following error when the object is in a subwindow. But it loads the waveform...

<img width="501" alt="Bildschirmfoto 2022-09-26 um 11 11 01" src="https://user-images.githubusercontent.com/39628224/192238806-fd100d46-d25c-49e5-b2c7-de4f761dd751.png">

**Comment by tremblap** [comment]
Thanks for the report. It is indeed a bug and on my todo list to fix. I'll update this thread when the fix is live

**Comment by tremblap** [comment]
good news - it seems to have disappeared in pd54-1 - bad news I cannot seem to reproduce anymore. I'm chasing

**Comment by tremblap** [comment]
(if you have a patch to reproduce, that would help me. I promise I won't take a year to reply, I'm deep in TCL now so I'm chasing that)

**Comment by tremblap** [comment]
new nightly should fix it
