### ISSUE TITLE
Bug: Pure Data Linux package misses almost all "Analyse Data" objects

### ISSUE THREAD

**Issue by alexdrymonitis** [flucoma/flucoma-pd#96]
### Please tell us what you were doing! You can include code and files by drag and dropping them into the text area.

All the objects in the "Analyse Data" section of the FluidCorpusManipulationOverview file are missing, except for [fluid.stats] and [fluid.bufstats]. I downloaded the Linux package from FluCoMa's website. I'm on Pd-0.54-0.

### What was the expected result?

The .pd_linux files of these objects should be in the library directory, but they are missing.

### What was the actual result?

Pd can't create these objects, since their binaries are missing.

### What operating system were you using?

Linux

### Operating system version

Debian 12

### FluCoMa Version

Not sure, the latest from FluCoMa's website at time of bug submission.

**Comment by tremblap** [comment]
Hello! Please read the installation instructions: it is a library and has to be installed properly (they are all part of the fluid.libmanipulation object). https://learn.flucoma.org/installation/pd/

**Comment by alexdrymonitis** [comment]
Oops, you're right. Sorry for the hasty bug report and thanks for getting back so quickly!
